### ISSUE TITLE
Package fails to compile. Missing 'GluonGui' namespace not included.

### ISSUE THREAD

**Issue by ErnSur** [ShiJbey/Anansi#13]
The _Runtime/Simulation/Simulation.cs_ contains line
```
using GluonGui.WorkspaceWindow.Views.WorkspaceExplorer.Configuration;
```
it causes the compiler error:

> Packages/com.shijbey.anansi/Runtime/Simulation/Simulation.cs(1,7): error CS0246: The type or namespace name 'GluonGui' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ShiJbey** [comment]
Just saw this issue. It's from an unused using statement in one of the files. I'll put out a patch.

**Comment by ShiJbey** [comment]
Just pushed an update that should fix it. Try updating your Anasi version in your `manifest.json` file to 0.5.1.
